# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import psc_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/imagens', verbose_name='Imagem')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Login')),
                ('birth_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data de Nascimento')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Feminino', max_length=1, verbose_name='Sexo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta ativo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='E da equipe?')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('curso', models.CharField(max_length=50, verbose_name='Curso')),
                ('turno', models.CharField(max_length=20, verbose_name='Turno da dinamica')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('historico', models.FileField(upload_to='media/imagens', verbose_name='Historico')),
                ('curriculum', models.FileField(upload_to='media/imagens', verbose_name='Curriculum')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observacoes')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='E-mail lembrando da dinamica')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', psc_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Periodo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Periodo')),
            ],
        ),
        migrations.AddField(
            model_name='inscricao',
            name='areas',
            field=models.ManyToManyField(to='psc_app.Area'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psc_app.Periodo'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
